version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'

  florists:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
